# Generated by Django 3.1.6 on 2021-02-12 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iso', models.CharField(blank=True, default=None, max_length=2)),
                ('flag', models.FileField(upload_to='flags', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])])),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('type', models.CharField(choices=[('CTY', 'Country'), ('PRV', 'Province')], max_length=3)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.region')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirmed', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.PositiveIntegerField(blank=True, null=True)),
                ('deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('recovered', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.region')),
            ],
        ),
    ]
